#!/bin/bash
#SBATCH --nodes=1             
#SBATCH --ntasks-per-node=1      
#SBATCH --time=04:00:00             
#SBATCH --account=eafeerc 
#SBATCH --job-name=plasmasheath
#SBATCH --output=job_output_filename.%j.out  # %j will be replaced with the job ID
#SBATCH --partition=short

module load PrgEnv-gnu
srun -n 1 ./*.ex inputs1d
