VIDYUT_DIR ?= ../../../

PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

DIM       = 2

COMP	   = llvm

USE_MPI    = FALSE
USE_OMP    = FALSE 
USE_CUDA   = FALSE

Bpack   := ./Make.package 
Blocs   := . 

include ${VIDYUT_DIR}/test/Make.vidyut
