#!/bin/bash

# Prompt the user to input the source directory, file name, and destination directory
echo "Enter the source directory:"
read source_dir

echo "Enter the destination directory:"
read dest_dir

# Check if the source file exists
 
  # Copy the file to the destination directory
  cp "$source_dir"/*.H "$dest_dir/"
  cp "$source_dir"/*.cpp "$dest_dir/"
  cp "$source_dir"/Make* "$dest_dir/"
  cp "$source_dir"/GNU* "$dest_dir/"
  cp "$source_dir"/*.yaml "$dest_dir/"
  cp "$source_dir"/inputs* "$dest_dir/"
  cp "$source_dir"/clean* "$dest_dir/"
  cp "$source_dir"/slurm* "$dest_dir/"
  cp "$source_dir"/contour_plotter.py "$dest_dir/"
  cp "$source_dir"/copy_script* "$dest_dir/"  
   
  echo "File copied successfully to $dest_dir."

